// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

RendererInfo createRenderer({
  required int width,
  required int height,
  required String sceneType,
}) => RustLib.instance.api.crateApiCreateRenderer(
  width: width,
  height: height,
  sceneType: sceneType,
);

void disposeRenderer({required BigInt handle}) =>
    RustLib.instance.api.crateApiDisposeRenderer(handle: handle);

Future<bool> requestFrame({required BigInt handle}) =>
    RustLib.instance.api.crateApiRequestFrame(handle: handle);

void startAnimation({required BigInt handle}) =>
    RustLib.instance.api.crateApiStartAnimation(handle: handle);

void stopAnimation({required BigInt handle}) =>
    RustLib.instance.api.crateApiStopAnimation(handle: handle);

void setBoolParam({
  required BigInt handle,
  required String key,
  required bool value,
}) => RustLib.instance.api.crateApiSetBoolParam(
  handle: handle,
  key: key,
  value: value,
);

void setFloatParam({
  required BigInt handle,
  required String key,
  required double value,
}) => RustLib.instance.api.crateApiSetFloatParam(
  handle: handle,
  key: key,
  value: value,
);

void setVec4Param({
  required BigInt handle,
  required String key,
  required List<double> value,
}) => RustLib.instance.api.crateApiSetVec4Param(
  handle: handle,
  key: key,
  value: value,
);

void invokeCommand({
  required BigInt handle,
  required String command,
  required String payload,
}) => RustLib.instance.api.crateApiInvokeCommand(
  handle: handle,
  command: command,
  payload: payload,
);

/// Push the editor scene tree (JSON) into the Bevy renderer. The renderer diffs
/// it against the current ECS world and spawns/updates/despawns entities.
void setScene({required BigInt handle, required String json}) =>
    RustLib.instance.api.crateApiSetScene(handle: handle, json: json);

/// JSON listing every registered Bevy component type:
/// `[ { "type_path": "...", "short_name": "..." }, ... ]`.
String listComponentTypes({required BigInt handle}) =>
    RustLib.instance.api.crateApiListComponentTypes(handle: handle);

/// JSON field-level description of one component type, or null if the type path
/// is not registered: `{ "type_path", "short_name", "kind", "fields": [ {
/// "name", "type_path", "kind", "default" } ] }`.
String? describeComponent({required BigInt handle, required String typePath}) =>
    RustLib.instance.api.crateApiDescribeComponent(
      handle: handle,
      typePath: typePath,
    );

/// Serialize the editor scene to a native Bevy `.scn.ron` file at `path`.
void saveScene({required BigInt handle, required String path}) =>
    RustLib.instance.api.crateApiSaveScene(handle: handle, path: path);

/// Load a native Bevy `.scn`/`.scn.ron` file into the live world.
void loadScene({required BigInt handle, required String path}) =>
    RustLib.instance.api.crateApiLoadScene(handle: handle, path: path);

/// Raycast a viewport pixel; returns the hit entity's editor id (or null).
String? pick({required BigInt handle, required double x, required double y}) =>
    RustLib.instance.api.crateApiPick(handle: handle, x: x, y: y);

/// Set the current selection by editor id (null clears). Drives the gizmo draw.
void selectEntity({required BigInt handle, String? id}) =>
    RustLib.instance.api.crateApiSelectEntity(handle: handle, id: id);

/// Set the active transform gizmo mode: "translate" | "rotate" | "scale" | "none".
void setGizmoMode({required BigInt handle, required String mode}) =>
    RustLib.instance.api.crateApiSetGizmoMode(handle: handle, mode: mode);

/// Orbit the camera around its focus point (Alt+LMB drag).
void cameraOrbit({
  required BigInt handle,
  required double dx,
  required double dy,
}) => RustLib.instance.api.crateApiCameraOrbit(handle: handle, dx: dx, dy: dy);

/// Pan the camera focus in the view plane (MMB drag).
void cameraPan({
  required BigInt handle,
  required double dx,
  required double dy,
}) => RustLib.instance.api.crateApiCameraPan(handle: handle, dx: dx, dy: dy);

/// Zoom toward/away from the focus (scroll wheel). Positive delta = zoom out.
void cameraZoom({required BigInt handle, required double delta}) =>
    RustLib.instance.api.crateApiCameraZoom(handle: handle, delta: delta);

/// Free-look rotate in place (RMB drag).
void cameraLook({
  required BigInt handle,
  required double dx,
  required double dy,
}) => RustLib.instance.api.crateApiCameraLook(handle: handle, dx: dx, dy: dy);

/// Fly the camera along its basis (RMB + WASD). forward/right/up in [-1,1].
void cameraFly({
  required BigInt handle,
  required double forward,
  required double right,
  required double up,
  required double dt,
}) => RustLib.instance.api.crateApiCameraFly(
  handle: handle,
  forward: forward,
  right: right,
  up: up,
  dt: dt,
);

/// Begin a gizmo drag at a viewport pixel. Returns true if a handle was grabbed
/// (the caller should then consume the drag rather than treating it as a pick).
bool dragBegin({
  required BigInt handle,
  required double x,
  required double y,
}) => RustLib.instance.api.crateApiDragBegin(handle: handle, x: x, y: y);

/// Continue a gizmo drag. Returns the selected entity's new transform (or null
/// if nothing changed / no active drag).
DragTransform? dragUpdate({
  required BigInt handle,
  required double x,
  required double y,
}) => RustLib.instance.api.crateApiDragUpdate(handle: handle, x: x, y: y);

/// End the current gizmo drag.
void dragEnd({required BigInt handle}) =>
    RustLib.instance.api.crateApiDragEnd(handle: handle);

/// Update the hovered gizmo handle at a viewport pixel (Unity-style highlight).
void setHover({required BigInt handle, required double x, required double y}) =>
    RustLib.instance.api.crateApiSetHover(handle: handle, x: x, y: y);

BackendInfo getBackendInfo({required BigInt handle}) =>
    RustLib.instance.api.crateApiGetBackendInfo(handle: handle);

void resizeRenderer({
  required BigInt handle,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiResizeRenderer(
  handle: handle,
  width: width,
  height: height,
);

/// Attach a Metal texture to the renderer (macOS / iOS only).
///
/// `mtl_texture_ptr` is the raw pointer value of an `id<MTLTexture>` cast to
/// `usize`. The native Swift bridge creates the texture and passes its address
/// back to Dart, which forwards it here so Rust can render into it.
void attachMetalTexture({
  required BigInt handle,
  required BigInt mtlTexturePtr,
  required int width,
  required int height,
  required int bytesPerRow,
}) => RustLib.instance.api.crateApiAttachMetalTexture(
  handle: handle,
  mtlTexturePtr: mtlTexturePtr,
  width: width,
  height: height,
  bytesPerRow: bytesPerRow,
);

/// Create a DXGI shared-handle present surface (Windows only).
///
/// Returns the raw HANDLE value cast to `usize`. The native Windows bridge
/// receives this value via the method channel and passes it to the Flutter
/// GPU surface texture system.
BigInt createDxgiSurface({
  required BigInt handle,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiCreateDxgiSurface(
  handle: handle,
  width: width,
  height: height,
);

/// Ensure the Linux Vulkan DMA-BUF present target exists and is the right size.
void ensureLinuxPresent({
  required BigInt handle,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiEnsureLinuxPresent(
  handle: handle,
  width: width,
  height: height,
);

/// Export the current frame as a DMA-BUF file descriptor (Linux only).
///
/// The native Linux bridge receives these values via the method channel and
/// uses them to import the buffer into an EGL image / GL texture.
DmaBufExport? exportDmabuf({required BigInt handle}) =>
    RustLib.instance.api.crateApiExportDmabuf(handle: handle);

/// Returns `true` if DMA-BUF export is supported by the current Vulkan device.
bool linuxDmabufSupported({required BigInt handle}) =>
    RustLib.instance.api.crateApiLinuxDmabufSupported(handle: handle);

class BackendInfo {
  final String backend;
  final String deviceName;
  final String driver;

  const BackendInfo({
    required this.backend,
    required this.deviceName,
    required this.driver,
  });

  @override
  int get hashCode => backend.hashCode ^ deviceName.hashCode ^ driver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendInfo &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          deviceName == other.deviceName &&
          driver == other.driver;
}

class DmaBufExport {
  final int fd;
  final int width;
  final int height;
  final int stride;
  final int offset;
  final int fourcc;
  final int modifierLow;
  final int modifierHigh;

  const DmaBufExport({
    required this.fd,
    required this.width,
    required this.height,
    required this.stride,
    required this.offset,
    required this.fourcc,
    required this.modifierLow,
    required this.modifierHigh,
  });

  @override
  int get hashCode =>
      fd.hashCode ^
      width.hashCode ^
      height.hashCode ^
      stride.hashCode ^
      offset.hashCode ^
      fourcc.hashCode ^
      modifierLow.hashCode ^
      modifierHigh.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DmaBufExport &&
          runtimeType == other.runtimeType &&
          fd == other.fd &&
          width == other.width &&
          height == other.height &&
          stride == other.stride &&
          offset == other.offset &&
          fourcc == other.fourcc &&
          modifierLow == other.modifierLow &&
          modifierHigh == other.modifierHigh;
}

/// A transform returned to Dart after a gizmo drag (rotation is quat xyzw).
class DragTransform {
  final Float32List translation;
  final Float32List rotation;
  final Float32List scale;

  const DragTransform({
    required this.translation,
    required this.rotation,
    required this.scale,
  });

  @override
  int get hashCode => translation.hashCode ^ rotation.hashCode ^ scale.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DragTransform &&
          runtimeType == other.runtimeType &&
          translation == other.translation &&
          rotation == other.rotation &&
          scale == other.scale;
}

class RendererInfo {
  final BigInt handle;
  final BackendInfo backend;

  const RendererInfo({required this.handle, required this.backend});

  @override
  int get hashCode => handle.hashCode ^ backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RendererInfo &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          backend == other.backend;
}
