// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

RendererInfo createRenderer({required int width, required int height}) =>
    RustLib.instance.api.crateApiCreateRenderer(width: width, height: height);

void disposeRenderer({required BigInt handle}) =>
    RustLib.instance.api.crateApiDisposeRenderer(handle: handle);

Future<bool> requestFrame({required BigInt handle}) =>
    RustLib.instance.api.crateApiRequestFrame(handle: handle);

void startAnimation({required BigInt handle}) =>
    RustLib.instance.api.crateApiStartAnimation(handle: handle);

void stopAnimation({required BigInt handle}) =>
    RustLib.instance.api.crateApiStopAnimation(handle: handle);

void setBoolParam({
  required BigInt handle,
  required String key,
  required bool value,
}) => RustLib.instance.api.crateApiSetBoolParam(
  handle: handle,
  key: key,
  value: value,
);

void setFloatParam({
  required BigInt handle,
  required String key,
  required double value,
}) => RustLib.instance.api.crateApiSetFloatParam(
  handle: handle,
  key: key,
  value: value,
);

void setVec4Param({
  required BigInt handle,
  required String key,
  required List<double> value,
}) => RustLib.instance.api.crateApiSetVec4Param(
  handle: handle,
  key: key,
  value: value,
);

void invokeCommand({
  required BigInt handle,
  required String command,
  required String payload,
}) => RustLib.instance.api.crateApiInvokeCommand(
  handle: handle,
  command: command,
  payload: payload,
);

BackendInfo getBackendInfo({required BigInt handle}) =>
    RustLib.instance.api.crateApiGetBackendInfo(handle: handle);

class BackendInfo {
  final String backend;
  final String deviceName;
  final String driver;

  const BackendInfo({
    required this.backend,
    required this.deviceName,
    required this.driver,
  });

  @override
  int get hashCode => backend.hashCode ^ deviceName.hashCode ^ driver.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackendInfo &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          deviceName == other.deviceName &&
          driver == other.driver;
}

class RendererInfo {
  final BigInt handle;
  final BackendInfo backend;

  const RendererInfo({required this.handle, required this.backend});

  @override
  int get hashCode => handle.hashCode ^ backend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RendererInfo &&
          runtimeType == other.runtimeType &&
          handle == other.handle &&
          backend == other.backend;
}
