// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 8055223;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flutter_wgpu_texture',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  void crateApiAttachMetalTexture({
    required BigInt handle,
    required BigInt mtlTexturePtr,
    required int width,
    required int height,
    required int bytesPerRow,
  });

  void crateApiCameraFly({
    required BigInt handle,
    required double forward,
    required double right,
    required double up,
    required double dt,
  });

  void crateApiCameraLook({
    required BigInt handle,
    required double dx,
    required double dy,
  });

  void crateApiCameraOrbit({
    required BigInt handle,
    required double dx,
    required double dy,
  });

  void crateApiCameraPan({
    required BigInt handle,
    required double dx,
    required double dy,
  });

  void crateApiCameraZoom({required BigInt handle, required double delta});

  BigInt crateApiCreateDxgiSurface({
    required BigInt handle,
    required int width,
    required int height,
  });

  RendererInfo crateApiCreateRenderer({
    required int width,
    required int height,
    required String sceneType,
  });

  String? crateApiDescribeComponent({
    required BigInt handle,
    required String typePath,
  });

  void crateApiDisposeRenderer({required BigInt handle});

  bool crateApiDragBegin({
    required BigInt handle,
    required double x,
    required double y,
  });

  void crateApiDragEnd({required BigInt handle});

  DragTransform? crateApiDragUpdate({
    required BigInt handle,
    required double x,
    required double y,
  });

  void crateApiEnsureLinuxPresent({
    required BigInt handle,
    required int width,
    required int height,
  });

  DmaBufExport? crateApiExportDmabuf({required BigInt handle});

  BackendInfo crateApiGetBackendInfo({required BigInt handle});

  void crateApiInvokeCommand({
    required BigInt handle,
    required String command,
    required String payload,
  });

  bool crateApiLinuxDmabufSupported({required BigInt handle});

  String crateApiListComponentTypes({required BigInt handle});

  void crateApiLoadScene({required BigInt handle, required String path});

  String? crateApiPick({
    required BigInt handle,
    required double x,
    required double y,
  });

  Future<bool> crateApiRequestFrame({required BigInt handle});

  void crateApiResizeRenderer({
    required BigInt handle,
    required int width,
    required int height,
  });

  void crateApiSaveScene({required BigInt handle, required String path});

  void crateApiSelectEntity({required BigInt handle, String? id});

  void crateApiSetBoolParam({
    required BigInt handle,
    required String key,
    required bool value,
  });

  void crateApiSetFloatParam({
    required BigInt handle,
    required String key,
    required double value,
  });

  void crateApiSetGizmoMode({required BigInt handle, required String mode});

  void crateApiSetHover({
    required BigInt handle,
    required double x,
    required double y,
  });

  void crateApiSetScene({required BigInt handle, required String json});

  void crateApiSetVec4Param({
    required BigInt handle,
    required String key,
    required List<double> value,
  });

  void crateApiStartAnimation({required BigInt handle});

  void crateApiStopAnimation({required BigInt handle});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  void crateApiAttachMetalTexture({
    required BigInt handle,
    required BigInt mtlTexturePtr,
    required int width,
    required int height,
    required int bytesPerRow,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_usize(mtlTexturePtr, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_u_32(bytesPerRow, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiAttachMetalTextureConstMeta,
        argValues: [handle, mtlTexturePtr, width, height, bytesPerRow],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAttachMetalTextureConstMeta => const TaskConstMeta(
    debugName: "attach_metal_texture",
    argNames: ["handle", "mtlTexturePtr", "width", "height", "bytesPerRow"],
  );

  @override
  void crateApiCameraFly({
    required BigInt handle,
    required double forward,
    required double right,
    required double up,
    required double dt,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(forward, serializer);
          sse_encode_f_32(right, serializer);
          sse_encode_f_32(up, serializer);
          sse_encode_f_32(dt, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraFlyConstMeta,
        argValues: [handle, forward, right, up, dt],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraFlyConstMeta => const TaskConstMeta(
    debugName: "camera_fly",
    argNames: ["handle", "forward", "right", "up", "dt"],
  );

  @override
  void crateApiCameraLook({
    required BigInt handle,
    required double dx,
    required double dy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(dx, serializer);
          sse_encode_f_32(dy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraLookConstMeta,
        argValues: [handle, dx, dy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraLookConstMeta => const TaskConstMeta(
    debugName: "camera_look",
    argNames: ["handle", "dx", "dy"],
  );

  @override
  void crateApiCameraOrbit({
    required BigInt handle,
    required double dx,
    required double dy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(dx, serializer);
          sse_encode_f_32(dy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraOrbitConstMeta,
        argValues: [handle, dx, dy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraOrbitConstMeta => const TaskConstMeta(
    debugName: "camera_orbit",
    argNames: ["handle", "dx", "dy"],
  );

  @override
  void crateApiCameraPan({
    required BigInt handle,
    required double dx,
    required double dy,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(dx, serializer);
          sse_encode_f_32(dy, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraPanConstMeta,
        argValues: [handle, dx, dy],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraPanConstMeta => const TaskConstMeta(
    debugName: "camera_pan",
    argNames: ["handle", "dx", "dy"],
  );

  @override
  void crateApiCameraZoom({required BigInt handle, required double delta}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(delta, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCameraZoomConstMeta,
        argValues: [handle, delta],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCameraZoomConstMeta => const TaskConstMeta(
    debugName: "camera_zoom",
    argNames: ["handle", "delta"],
  );

  @override
  BigInt crateApiCreateDxgiSurface({
    required BigInt handle,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateDxgiSurfaceConstMeta,
        argValues: [handle, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateDxgiSurfaceConstMeta => const TaskConstMeta(
    debugName: "create_dxgi_surface",
    argNames: ["handle", "width", "height"],
  );

  @override
  RendererInfo crateApiCreateRenderer({
    required int width,
    required int height,
    required String sceneType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          sse_encode_String(sceneType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_renderer_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCreateRendererConstMeta,
        argValues: [width, height, sceneType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateRendererConstMeta => const TaskConstMeta(
    debugName: "create_renderer",
    argNames: ["width", "height", "sceneType"],
  );

  @override
  String? crateApiDescribeComponent({
    required BigInt handle,
    required String typePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(typePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDescribeComponentConstMeta,
        argValues: [handle, typePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDescribeComponentConstMeta => const TaskConstMeta(
    debugName: "describe_component",
    argNames: ["handle", "typePath"],
  );

  @override
  void crateApiDisposeRenderer({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDisposeRendererConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDisposeRendererConstMeta =>
      const TaskConstMeta(debugName: "dispose_renderer", argNames: ["handle"]);

  @override
  bool crateApiDragBegin({
    required BigInt handle,
    required double x,
    required double y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDragBeginConstMeta,
        argValues: [handle, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDragBeginConstMeta => const TaskConstMeta(
    debugName: "drag_begin",
    argNames: ["handle", "x", "y"],
  );

  @override
  void crateApiDragEnd({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDragEndConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDragEndConstMeta =>
      const TaskConstMeta(debugName: "drag_end", argNames: ["handle"]);

  @override
  DragTransform? crateApiDragUpdate({
    required BigInt handle,
    required double x,
    required double y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_drag_transform,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiDragUpdateConstMeta,
        argValues: [handle, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDragUpdateConstMeta => const TaskConstMeta(
    debugName: "drag_update",
    argNames: ["handle", "x", "y"],
  );

  @override
  void crateApiEnsureLinuxPresent({
    required BigInt handle,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiEnsureLinuxPresentConstMeta,
        argValues: [handle, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnsureLinuxPresentConstMeta => const TaskConstMeta(
    debugName: "ensure_linux_present",
    argNames: ["handle", "width", "height"],
  );

  @override
  DmaBufExport? crateApiExportDmabuf({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_dma_buf_export,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiExportDmabufConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiExportDmabufConstMeta =>
      const TaskConstMeta(debugName: "export_dmabuf", argNames: ["handle"]);

  @override
  BackendInfo crateApiGetBackendInfo({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_backend_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiGetBackendInfoConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetBackendInfoConstMeta =>
      const TaskConstMeta(debugName: "get_backend_info", argNames: ["handle"]);

  @override
  void crateApiInvokeCommand({
    required BigInt handle,
    required String command,
    required String payload,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(command, serializer);
          sse_encode_String(payload, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiInvokeCommandConstMeta,
        argValues: [handle, command, payload],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInvokeCommandConstMeta => const TaskConstMeta(
    debugName: "invoke_command",
    argNames: ["handle", "command", "payload"],
  );

  @override
  bool crateApiLinuxDmabufSupported({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLinuxDmabufSupportedConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLinuxDmabufSupportedConstMeta =>
      const TaskConstMeta(
        debugName: "linux_dmabuf_supported",
        argNames: ["handle"],
      );

  @override
  String crateApiListComponentTypes({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiListComponentTypesConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiListComponentTypesConstMeta => const TaskConstMeta(
    debugName: "list_component_types",
    argNames: ["handle"],
  );

  @override
  void crateApiLoadScene({required BigInt handle, required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiLoadSceneConstMeta,
        argValues: [handle, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadSceneConstMeta => const TaskConstMeta(
    debugName: "load_scene",
    argNames: ["handle", "path"],
  );

  @override
  String? crateApiPick({
    required BigInt handle,
    required double x,
    required double y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPickConstMeta,
        argValues: [handle, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPickConstMeta =>
      const TaskConstMeta(debugName: "pick", argNames: ["handle", "x", "y"]);

  @override
  Future<bool> crateApiRequestFrame({required BigInt handle}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiRequestFrameConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiRequestFrameConstMeta =>
      const TaskConstMeta(debugName: "request_frame", argNames: ["handle"]);

  @override
  void crateApiResizeRenderer({
    required BigInt handle,
    required int width,
    required int height,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_u_32(width, serializer);
          sse_encode_u_32(height, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiResizeRendererConstMeta,
        argValues: [handle, width, height],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResizeRendererConstMeta => const TaskConstMeta(
    debugName: "resize_renderer",
    argNames: ["handle", "width", "height"],
  );

  @override
  void crateApiSaveScene({required BigInt handle, required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveSceneConstMeta,
        argValues: [handle, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveSceneConstMeta => const TaskConstMeta(
    debugName: "save_scene",
    argNames: ["handle", "path"],
  );

  @override
  void crateApiSelectEntity({required BigInt handle, String? id}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_opt_String(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSelectEntityConstMeta,
        argValues: [handle, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSelectEntityConstMeta => const TaskConstMeta(
    debugName: "select_entity",
    argNames: ["handle", "id"],
  );

  @override
  void crateApiSetBoolParam({
    required BigInt handle,
    required String key,
    required bool value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(key, serializer);
          sse_encode_bool(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetBoolParamConstMeta,
        argValues: [handle, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetBoolParamConstMeta => const TaskConstMeta(
    debugName: "set_bool_param",
    argNames: ["handle", "key", "value"],
  );

  @override
  void crateApiSetFloatParam({
    required BigInt handle,
    required String key,
    required double value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(key, serializer);
          sse_encode_f_32(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetFloatParamConstMeta,
        argValues: [handle, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetFloatParamConstMeta => const TaskConstMeta(
    debugName: "set_float_param",
    argNames: ["handle", "key", "value"],
  );

  @override
  void crateApiSetGizmoMode({required BigInt handle, required String mode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetGizmoModeConstMeta,
        argValues: [handle, mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetGizmoModeConstMeta => const TaskConstMeta(
    debugName: "set_gizmo_mode",
    argNames: ["handle", "mode"],
  );

  @override
  void crateApiSetHover({
    required BigInt handle,
    required double x,
    required double y,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_f_32(x, serializer);
          sse_encode_f_32(y, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetHoverConstMeta,
        argValues: [handle, x, y],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetHoverConstMeta => const TaskConstMeta(
    debugName: "set_hover",
    argNames: ["handle", "x", "y"],
  );

  @override
  void crateApiSetScene({required BigInt handle, required String json}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(json, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetSceneConstMeta,
        argValues: [handle, json],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetSceneConstMeta =>
      const TaskConstMeta(debugName: "set_scene", argNames: ["handle", "json"]);

  @override
  void crateApiSetVec4Param({
    required BigInt handle,
    required String key,
    required List<double> value,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          sse_encode_String(key, serializer);
          sse_encode_list_prim_f_32_loose(value, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetVec4ParamConstMeta,
        argValues: [handle, key, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetVec4ParamConstMeta => const TaskConstMeta(
    debugName: "set_vec4_param",
    argNames: ["handle", "key", "value"],
  );

  @override
  void crateApiStartAnimation({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStartAnimationConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartAnimationConstMeta =>
      const TaskConstMeta(debugName: "start_animation", argNames: ["handle"]);

  @override
  void crateApiStopAnimation({required BigInt handle}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(handle, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 33)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiStopAnimationConstMeta,
        argValues: [handle],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopAnimationConstMeta =>
      const TaskConstMeta(debugName: "stop_animation", argNames: ["handle"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BackendInfo dco_decode_backend_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BackendInfo(
      backend: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      driver: dco_decode_String(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DmaBufExport dco_decode_box_autoadd_dma_buf_export(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_dma_buf_export(raw);
  }

  @protected
  DragTransform dco_decode_box_autoadd_drag_transform(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_drag_transform(raw);
  }

  @protected
  DmaBufExport dco_decode_dma_buf_export(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return DmaBufExport(
      fd: dco_decode_i_32(arr[0]),
      width: dco_decode_u_32(arr[1]),
      height: dco_decode_u_32(arr[2]),
      stride: dco_decode_i_32(arr[3]),
      offset: dco_decode_i_32(arr[4]),
      fourcc: dco_decode_i_32(arr[5]),
      modifierLow: dco_decode_u_32(arr[6]),
      modifierHigh: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  DragTransform dco_decode_drag_transform(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DragTransform(
      translation: dco_decode_list_prim_f_32_strict(arr[0]),
      rotation: dco_decode_list_prim_f_32_strict(arr[1]),
      scale: dco_decode_list_prim_f_32_strict(arr[2]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<double>;
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DmaBufExport? dco_decode_opt_box_autoadd_dma_buf_export(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_dma_buf_export(raw);
  }

  @protected
  DragTransform? dco_decode_opt_box_autoadd_drag_transform(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_drag_transform(raw);
  }

  @protected
  RendererInfo dco_decode_renderer_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RendererInfo(
      handle: dco_decode_u_64(arr[0]),
      backend: dco_decode_backend_info(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BackendInfo sse_decode_backend_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_backend = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_driver = sse_decode_String(deserializer);
    return BackendInfo(
      backend: var_backend,
      deviceName: var_deviceName,
      driver: var_driver,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DmaBufExport sse_decode_box_autoadd_dma_buf_export(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_dma_buf_export(deserializer));
  }

  @protected
  DragTransform sse_decode_box_autoadd_drag_transform(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_drag_transform(deserializer));
  }

  @protected
  DmaBufExport sse_decode_dma_buf_export(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_fd = sse_decode_i_32(deserializer);
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    var var_stride = sse_decode_i_32(deserializer);
    var var_offset = sse_decode_i_32(deserializer);
    var var_fourcc = sse_decode_i_32(deserializer);
    var var_modifierLow = sse_decode_u_32(deserializer);
    var var_modifierHigh = sse_decode_u_32(deserializer);
    return DmaBufExport(
      fd: var_fd,
      width: var_width,
      height: var_height,
      stride: var_stride,
      offset: var_offset,
      fourcc: var_fourcc,
      modifierLow: var_modifierLow,
      modifierHigh: var_modifierHigh,
    );
  }

  @protected
  DragTransform sse_decode_drag_transform(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_translation = sse_decode_list_prim_f_32_strict(deserializer);
    var var_rotation = sse_decode_list_prim_f_32_strict(deserializer);
    var var_scale = sse_decode_list_prim_f_32_strict(deserializer);
    return DragTransform(
      translation: var_translation,
      rotation: var_rotation,
      scale: var_scale,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DmaBufExport? sse_decode_opt_box_autoadd_dma_buf_export(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_dma_buf_export(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DragTransform? sse_decode_opt_box_autoadd_drag_transform(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_drag_transform(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RendererInfo sse_decode_renderer_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_handle = sse_decode_u_64(deserializer);
    var var_backend = sse_decode_backend_info(deserializer);
    return RendererInfo(handle: var_handle, backend: var_backend);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_backend_info(BackendInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.backend, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.driver, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_dma_buf_export(
    DmaBufExport self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_dma_buf_export(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_drag_transform(
    DragTransform self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_drag_transform(self, serializer);
  }

  @protected
  void sse_encode_dma_buf_export(DmaBufExport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.fd, serializer);
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
    sse_encode_i_32(self.stride, serializer);
    sse_encode_i_32(self.offset, serializer);
    sse_encode_i_32(self.fourcc, serializer);
    sse_encode_u_32(self.modifierLow, serializer);
    sse_encode_u_32(self.modifierHigh, serializer);
  }

  @protected
  void sse_encode_drag_transform(DragTransform self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_f_32_strict(self.translation, serializer);
    sse_encode_list_prim_f_32_strict(self.rotation, serializer);
    sse_encode_list_prim_f_32_strict(self.scale, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(
      self is Float32List ? self : Float32List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_dma_buf_export(
    DmaBufExport? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_dma_buf_export(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_drag_transform(
    DragTransform? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_drag_transform(self, serializer);
    }
  }

  @protected
  void sse_encode_renderer_info(RendererInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.handle, serializer);
    sse_encode_backend_info(self.backend, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
