// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

@Deprecated('Template API removed. Expose your own Rust methods instead.')
Never greet({required String name}) =>
    throw UnsupportedError(
      'Template greet() API was removed from flutter_wgpu_texture.',
    );
