name: flutter_wgpu_texture_spinning_cube
publish_to: none

environment:
  sdk: ^3.8.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_wgpu_texture:
    path: ../..

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
